{
    "swagger": "2.0",
    "info": {
        "description": "Welcome to QuantiModo API! QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do) or contact us at <api@quantimo.do>.\n\n\n\n\n\n\n\n\nBefore you get started, you will need to:\n* Sign in/Sign up, and add some data at [https://app.quantimo.do/api/v2/account/connectors](https://app.quantimo.do/api/v2/account/connectors) to try out the API for yourself\n* Create an app to get you[...]",
        "version": "2.0.6",
        "title": "QuantiModo",
        "termsOfService": "https://quantimo.do/terms/",
        "contact": {
            "name": "info@quantimo.do"
        }
    },
    "basePath": "/api",
    "host": "app.quantimo.do",
    "schemes": [
        "https"
    ],
    "security": [
        {
            "oauth2": [
                "basic",
                "readmeasurements",
                "writemeasurements"
            ]
        },
        {
            "internalApiKey": []
        }
    ],
    "paths": {
        "/v1/connect.js": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "Get embeddable connect javascript",
                "description": "Get embeddable connect javascript. Usage:\n\n  - Embedding in applications with popups for 3rd-party authentication\nwindows.\n\n    Use `qmSetupInPopup` function after connecting `connect.js`.\n\n  - Embedding in applications with popups for 3rd-party authentication\nwindows.\n\n    Requires a selector to block. It will be embedded in this block.\n\n    Use `qmSetupOnPage` function after connecting `connect.js`.\n\n  - Embedding in mobile applications without pop[...]"
            }
        },
        "/v1/connect/mobile": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "Mobile connect page",
                "description": "This page is designed to be opened in a webview.  Instead of using popup authentication boxes, it uses redirection. You can include the user's access_token as a URL parameter like https://app.quantimo.do/api/v1/connect/mobile?access_token=123"
            }
        },
        "/v1/connectors/list": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "List of Connectors",
                "description": "A connector pulls data from other data providers using their API or a screenscraper. Returns a list of all available connectors and information about them such as their id, name, whether the user has provided access, logo url, connection instructions, and the update history.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/connectors/{connector}/connect": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "Obtain a token from 3rd party data source",
                "description": "Attempt to obtain a token from the data provider, store it in the database. With this, the connector to continue to obtain new user data until the token is revoked.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/connectors/{connector}/connectParameter": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "Connect Parameter",
                "description": "Returns instructions that describe what parameters and endpoint to use to connect to the given data provider.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/connectors/{connector}/connectInstructions": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "Connection Instructions",
                "description": "Returns instructions that describe what parameters and endpoint to use to connect to the given data provider.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/connectors/{connector}/disconnect": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "Delete stored connection info",
                "description": "The disconnect method deletes any stored tokens or connection information from the connectors database.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/connectors/{connector}/info": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "Get connector info for user",
                "description": "Returns information about the connector such as the connector id, whether or not is connected for this user (i.e. we have a token or credentials), and its update history for the user.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/connectors/{connector}/update": {
            "get": {
                "tags": [
                    "connectors"
                ],
                "summary": "Sync with data source",
                "description": "The update method tells the QM Connector Framework to check with the data provider (such as Fitbit or MyFitnessPal) and retrieve any new measurements available.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/correlations": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Get correlations",
                "description": "Get correlations based on data from a single user.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/aggregatedCorrelations": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Get aggregated correlations",
                "description": "Get correlations based on the anonymized aggregate data from all QuantiModo users.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "correlations"
                ],
                "summary": "Store or Update a Correlation",
                "description": "Add correlation",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/public/correlations/search/{search}": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Get average correlations for variables containing search term",
                "description": "Returns the average correlations from all users for all public variables that contain the characters in the search query. Returns average of all users public variable correlations with a specified cause or effect.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/variables/{variableName}/public/causes": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Search public correlations for a given effect",
                "description": "Returns average of all correlations and votes for all public cause variables for a given effect",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/variables/{variableName}/public/effects": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Search public correlations for a given cause",
                "description": "Returns average of all correlations and votes for all public cause variables for a given cause",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/variables/{variableName}/causes": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Search user correlations for a given effect",
                "description": "Returns average of all correlations and votes for all user cause variables for a given effect",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/variables/{variableName}/effects": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Search user correlations for a given cause",
                "description": "Returns average of all correlations and votes for all user effect variables for a given cause",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/organizations/{organizationId}/users/{userId}/variables/{variableName}/causes": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Search user correlations for a given cause",
                "description": "Returns average of all correlations and votes for all user cause variables for a given cause. If parameter \"include_public\" is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/organizations/{organizationId}/users/{userId}/variables/{variableName}/effects": {
            "get": {
                "tags": [
                    "correlations"
                ],
                "summary": "Search user correlations for a given cause",
                "description": "Returns average of all correlations and votes for all user cause variables for a given effect. If parameter \"include_public\" is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/measurements": {
            "get": {
                "tags": [
                    "measurements"
                ],
                "summary": "Get measurements for this user",
                "description": "Measurements are any value that can be recorded like daily steps, a mood rating, or apples eaten. <br>Supported filter parameters:<br><ul><li><b>value</b> - Value of measurement</li><li><b>lastUpdated</b> - The time that this measurement was created or last updated in the UTC format \"YYYY-MM-DDThh:mm:ss\"</li></ul><br>",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "measurements"
                ],
                "summary": "Post a new set or update existing measurements to the database",
                "description": "You can submit or update multiple measurements in a \"measurements\" sub-array.  If the variable these measurements correspond to does not already exist in the database, it will be automatically added.  The request body should look something like [{\"measurements\":[{\"startTime\":1439389320,\"value\":\"3\"}, {\"startTime\":1439389319,\"value\":\"2\"}],\"name\":\"Acne (out of 5)\",\"source\":\"QuantiModo\",\"category\":\"Symptoms\",\"combinationOperation\":\"MEAN\[...]",
                "security": [
                    {
                        "oauth2": [
                            "writemeasurements"
                        ]
                    }
                ]
            }
        },
        "/v1/measurements/delete": {
            "post": {
                "tags": [
                    "measurements"
                ],
                "summary": "Delete a measurement",
                "description": "Delete a previously submitted measurement",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/measurements/update": {
            "post": {
                "tags": [
                    "measurements"
                ],
                "summary": "Update a measurement",
                "description": "Delete a previously submitted measurement",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/measurements/{id}": {
            "get": {
                "tags": [
                    "measurements"
                ],
                "summary": "Get Measurement",
                "description": "Get Measurement",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            },
            "put": {
                "tags": [
                    "measurements"
                ],
                "summary": "Update Measurement",
                "description": "Update Measurement",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "measurements"
                ],
                "summary": "Delete Measurement",
                "description": "Delete Measurement",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/application/connections": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get all Connections",
                "description": "Get all Connections"
            }
        },
        "/v2/application/credentials": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get all Credentials",
                "description": "Get all Credentials"
            }
        },
        "/v2/application/measurements": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get measurements for all users using your application",
                "description": "Measurements are any value that can be recorded like daily steps, a mood rating, or apples eaten."
            }
        },
        "/v2/application/trackingReminders": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get tracking reminders",
                "description": "Get the variable id, frequency, and default value for the user tracking reminders "
            }
        },
        "/v2/application/updates": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get all Updates",
                "description": "Get all Updates"
            }
        },
        "/v2/application/userVariables": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get all UserVariables",
                "description": "Get all UserVariables"
            }
        },
        "/v2/application/userVariableRelationships": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get all UserVariableRelationships",
                "description": "Get all UserVariableRelationships"
            }
        },
        "/v2/application/variableUserSources": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get all VariableUserSources",
                "description": "Get all VariableUserSources"
            }
        },
        "/v2/application/votes": {
            "get": {
                "tags": [
                    "application endpoints"
                ],
                "summary": "Get all Votes",
                "description": "Get all Votes"
            }
        },
        "/v1/measurements/daily": {
            "get": {
                "tags": [
                    "measurements"
                ],
                "summary": "Get daily measurements for this user",
                "description": "Measurements are any value that can be recorded like daily steps, a mood rating, or apples eaten. <br>Supported filter parameters:<br><ul><li><b>value</b> - Value of measurement</li><li><b>lastUpdated</b> - The time that this measurement was created or last updated in the UTC format \"YYYY-MM-DDThh:mm:ss\"</li></ul><br>",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/measurements/request_csv": {
            "post": {
                "tags": [
                    "measurements"
                ],
                "summary": "Post Request for Measurements CSV",
                "description": "Use this endpoint to schedule a CSV export containing all user measurements to be emailed to the user within 24 hours.",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/measurements/request_xls": {
            "post": {
                "tags": [
                    "measurements"
                ],
                "summary": "Post Request for Measurements XLS",
                "description": "Use this endpoint to schedule a XLS export containing all user measurements to be emailed to the user within 24 hours.",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/measurements/request_pdf": {
            "post": {
                "tags": [
                    "measurements"
                ],
                "summary": "Post Request for Measurements PDF",
                "description": "Use this endpoint to schedule a PDF export containing all user measurements to be emailed to the user within 24 hours.",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/measurements/csv": {
            "get": {
                "tags": [
                    "measurements"
                ],
                "summary": "Get Measurements CSV",
                "description": "Download a CSV containing all user measurements",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/measurementsRange": {
            "get": {
                "tags": [
                    "measurements"
                ],
                "summary": "Get measurements range for this user",
                "description": "Get Unix time-stamp (epoch time) of the user's first and last measurements taken.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/measurementSources": {
            "post": {
                "tags": [
                    "measurements"
                ],
                "summary": "Add a data source",
                "description": "Add a life-tracking app or device to the QuantiModo list of data sources.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            },
            "get": {
                "tags": [
                    "measurements"
                ],
                "summary": "Get measurement sources",
                "description": "Returns a list of all the apps from which measurement data is obtained.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/oauth/authorize": {
            "get": {
                "tags": [
                    "authentication"
                ],
                "summary": "Request Authorization Code",
                "description": "You can implement OAuth2 authentication to your application using our **OAuth2** endpoints.  You need to redirect users to `/api/v2/oauth/authorize` endpoint to get an authorization code and include the parameters below.   This page will ask the user if they want to allow a client's application to submit or obtain data from their QM account. It will redirect the user to the url provided by the client application with the code as a query parameter or error in case [...]",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/oauth2/access_token": {
            "get": {
                "tags": [
                    "authentication"
                ],
                "summary": "Get a user access token",
                "description": "Client provides authorization token obtained from /api/v1/oauth2/authorize to this endpoint and receives an access token. Access token can then be used to query different API endpoints of QuantiModo.\n### Request Access Token\nAfter user approves your access to the given scope form the https:/app.quantimo.do/v2/oauth2/authorize endpoint, you'll receive an authorization code to request an access token. This time make a `POST` request to `/api/v2/oauth/access_token`[...]",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/auth/social/login": {
            "get": {
                "tags": [
                    "authentication"
                ],
                "summary": "First Setp in Social Authentication flow with JWT Token",
                "description": " Here is the flow for how social authentication works with a JWT Token\n\n1.**Client:** The client needs to open popup with social auth url (`https://app/quantimo.do/api/v2/auth/social/login?provider={provider}&redirectUrl={url}`) of server with `provider` and `redirectUrl`. (Url should be registered with our social apps. Facebook and Twitter are fine with any redirect url with the same domain base url but Google needs exact redirect url.)\n\n\n2.**Server:** The Q[...]",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/auth/social/authorizeCode": {
            "get": {
                "tags": [
                    "authentication"
                ],
                "summary": "Second Step in Social Authentication flow with JWT Token",
                "description": " Here is the flow for how social authentication works with a JWT Token\n\n1.**Client:** The client needs to open popup with social auth url (`https://app/quantimo.do/api/v2/auth/social/login?provider={provider}&redirectUrl={url}`) of server with `provider` and `redirectUrl`. (Url should be registered with our social apps. Facebook and Twitter are fine with any redirect url with the same domain base url but Google needs exact redirect url.)\n\n\n2.**Server:** The Q[...]",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v2/auth/social/authorizeToken": {
            "get": {
                "tags": [
                    "authentication"
                ],
                "summary": "Native Social Authentication",
                "description": "     \nIf you are using native authentication via Facebook or Google SDKs then you should use the following flow.\n\n\n1.**Client:** Using native authentication via your native mobile app, get an access token using the instructions provided by the Facebook SDK (https://developers.facebook.com/docs/facebook-login) or Google (https://developers.google.com/identity/protocols/OAuth2)\n\n\n2.**Client:** Send an Ajax request with provider name and access token on `https[...]",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/organizations/{organizationId}/users": {
            "post": {
                "tags": [
                    "organizations",
                    "user"
                ],
                "summary": "Get user tokens for existing users, create new users",
                "description": "Get user tokens for existing users, create new users"
            }
        },
        "/v1/pairs": {
            "get": {
                "tags": [
                    "pairs"
                ],
                "summary": "Get pairs",
                "description": "Pairs cause measurements with effect measurements grouped over the duration of action after the onset delay.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/pairsCsv": {
            "get": {
                "tags": [
                    "pairs"
                ],
                "summary": "Get pairs",
                "description": "Pairs cause measurements with effect measurements grouped over the duration of action after the onset delay.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/trackingReminders": {
            "get": {
                "tags": [
                    "reminders"
                ],
                "summary": "Get repeating tracking reminder settings",
                "description": "Users can be reminded to track certain variables at a specified frequency with a default value.  ",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "reminders"
                ],
                "summary": "Store a Tracking Reminder",
                "description": "This is to enable users to create reminders to track a variable with a default value at a specified frequency",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/trackingReminders/delete": {
            "post": {
                "tags": [
                    "reminders"
                ],
                "summary": "Delete tracking reminder",
                "description": "Delete previously created tracking reminder",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/trackingReminderNotifications": {
            "get": {
                "tags": [
                    "reminders"
                ],
                "summary": "Get specific pending tracking reminders",
                "description": "Specfic pending reminder instances that still need to be tracked.  ",
                "security": [
                    {
                        "quantimodo_oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/trackingReminderNotifications/snooze": {
            "post": {
                "tags": [
                    "reminders"
                ],
                "summary": "Snooze a pending tracking reminder",
                "description": "Changes the reminder time to now plus one hour",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/trackingReminderNotifications/skip": {
            "post": {
                "tags": [
                    "reminders"
                ],
                "summary": "Skip a pending tracking reminder",
                "description": "Deletes the pending tracking reminder",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/trackingReminderNotifications/track": {
            "post": {
                "tags": [
                    "reminders"
                ],
                "summary": "Track a pending tracking reminder",
                "description": "Adds the default measurement for the pending tracking reminder with the reminder time as the measurment start time",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/units": {
            "get": {
                "tags": [
                    "units"
                ],
                "summary": "Get all available units",
                "description": "Get all available units",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/unitCategories": {
            "get": {
                "tags": [
                    "units"
                ],
                "summary": "Get unit categories",
                "description": "Get a list of the categories of measurement units such as 'Distance', 'Duration', 'Energy', 'Frequency', 'Miscellany', 'Pressure', 'Proportion', 'Rating', 'Temperature', 'Volume', and 'Weight'.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/unitsVariable": {
            "get": {
                "tags": [
                    "units"
                ],
                "summary": "Units for Variable",
                "description": "Get a list of all possible units to use for a given variable",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/user/me": {
            "get": {
                "tags": [
                    "user"
                ],
                "summary": "Get all available units for variableGet authenticated user",
                "description": "Returns user info for the currently authenticated user.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/userTags": {
            "post": {
                "tags": [
                    "tags"
                ],
                "summary": "Post or update user tags or ingredients",
                "description": "This endpoint allows users to tag foods with their ingredients.  This information will then be used to infer the user intake of the different ingredients by just entering the foods. The inferred intake levels will then be used to determine the effects of different nutrients on the user during analysis.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/userTags/delete": {
            "post": {
                "tags": [
                    "tags"
                ],
                "summary": "Delete user tag or ingredient",
                "description": "Delete previously created user tags or ingredients.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/variables": {
            "post": {
                "tags": [
                    "variables"
                ],
                "summary": "Create Variables",
                "description": "Allows the client to create a new variable in the `variables` table.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            },
            "get": {
                "tags": [
                    "variables"
                ],
                "summary": "Get variables with user's settings",
                "description": "Get variables for which the user has measurements. If the user has specified variable settings, these are provided instead of the common variable defaults.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    },
                    {
                        "basicAuth": []
                    }
                ]
            }
        },
        "/v1/variables/{variableName}": {
            "get": {
                "tags": [
                    "variables"
                ],
                "summary": "Get info about a variable",
                "description": "Get all of the settings and information about a variable by its name. If the logged in user has modified the settings for the variable, these will be provided instead of the default settings for that variable.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/public/variables": {
            "get": {
                "tags": [
                    "variables"
                ],
                "summary": "Get public variables",
                "description": "This endpoint retrieves an array of all public variables. Public variables are things like foods, medications, symptoms, conditions, and anything not unique to a particular user. For instance, a telephone number or name would not be a public variable.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/public/variables/search/{search}": {
            "get": {
                "tags": [
                    "variables"
                ],
                "summary": "Get top 5 PUBLIC variables with the most correlations",
                "description": "Get top 5 PUBLIC variables with the most correlations containing the entered search characters. For example, search for 'mood' as an effect. Since 'Overall Mood' has a lot of correlations with other variables, it should be in the autocomplete list.<br>Supported filter parameters:<br><ul><li><b>category</b> - Category of Variable</li></ul><br>",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/variables/search/{search}": {
            "get": {
                "tags": [
                    "variables"
                ],
                "summary": "Get variables by search query",
                "description": "Get variables containing the search characters for which the currently logged in user has measurements. Used to provide auto-complete function in variable search boxes.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/userVariables": {
            "post": {
                "tags": [
                    "variables"
                ],
                "summary": "Update User Settings for a Variable",
                "description": "Users can change the parameters used in analysis of that variable such as the expected duration of action for a variable to have an effect, the estimated delay before the onset of action. In order to filter out erroneous data, they are able to set the maximum and minimum reasonable daily values for a variable.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/userVariables/delete": {
            "post": {
                "tags": [
                    "variables"
                ],
                "summary": "Delete All Measurements For Variable",
                "description": "Users can delete all of their measurements for a variable",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/userVariables/reset": {
            "post": {
                "tags": [
                    "variables"
                ],
                "summary": "Reset user settings for a variable to defaults",
                "description": "Reset user settings for a variable to defaults",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/variableCategories": {
            "get": {
                "tags": [
                    "variables"
                ],
                "summary": "Variable categories",
                "description": "The variable categories include Activity, Causes of Illness, Cognitive Performance, Conditions, Environment, Foods, Location, Miscellaneous, Mood, Nutrition, Physical Activity, Physique, Sleep, Social Interactions, Symptoms, Treatments, Vital Signs, and Work.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/votes": {
            "post": {
                "tags": [
                    "correlations",
                    "votes"
                ],
                "summary": "Post or update vote",
                "description": "This is to enable users to indicate their opinion on the plausibility of a causal relationship between a treatment and outcome. QuantiModo incorporates crowd-sourced plausibility estimations into their algorithm. This is done allowing user to indicate their view of the plausibility of each relationship with thumbs up/down buttons placed next to each prediction.",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        },
        "/v1/votes/delete": {
            "post": {
                "tags": [
                    "correlations",
                    "votes"
                ],
                "summary": "Delete vote",
                "description": "Delete previously posted vote",
                "security": [
                    {
                        "oauth2": [
                            "basic"
                        ]
                    }
                ]
            }
        }
    },
    "securityDefinitions": {
        "quantimodo_oauth2": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "/api/v2/oauth/authorize",
            "tokenUrl": "/api/v2/oauth/access_token",
            "scopes": {
                "basic": "Allows you to read user info (displayname, email, etc).",
                "readmeasurements": "Allows one to read a user's data",
                "writemeasurements": "Allows you to write user data"
            }
        },
        "basicAuth": {
            "type": "basic",
            "description": "HTTP Basic Authentication. Works over `HTTPS`"
        },
        "oauth2": {
            "type": "oauth2",
            "scopes": {
                "basic": "Basic authentication",
                "readmeasurements": "Grants read access to measurements and variables. Allows the client app to obtain the user's data.",
                "writemeasurements": "Grants write access to measurements and variables. Allows the client app to store user data."
            },
            "flow": "implicit",
            "authorizationUrl": "https://app.quantimo.do/api/v1/oauth2/authorize"
        },
        "internalApiKey": {
            "type": "apiKey",
            "in": "header",
            "name": "api_key"
        }
    }
}